version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - MONGODB_URI=mongodb://monuser:monpassword@mongo:27017/test?authSource=admin
            - NEXTAUTH_SECRET=np2eKckZAIMQoQSzDsuTf2HhXfY4YScgORF5VJT/3BY=
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        depends_on:
          - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=monuser
            - MONGO_INITDB_ROOT_PASSWORD=monpassword
        volumes:
            - mongo-db:/data/db
        ports:
            - "27017:27017"
volumes:
    mongo-db:
    node_modules: